version: "3.7"

services:
  api:
    build: "api"
    command: "runserver 0.0.0.0:80"
    ports:
      - 8001:80

  web:
    build: "web"
    command: "npm run dev -- -H 0.0.0.0 -p 80"
    volumes:
      - ./web/assets:/usr/src/app/assets
      - ./web/components:/usr/src/app/components
      - ./web/layouts:/usr/src/app/layouts
      - ./web/middleware:/usr/src/app/middleware
      - ./web/pages:/usr/src/app/pages
      - ./web/plugins:/usr/src/app/plugins
      - ./web/static:/usr/src/app/static
      - ./web/store:/usr/src/app/store
      - ${PWD}/web/nuxt.config.js:/usr/src/app/nuxt.config.js
    ports:
      - 8000:80
