version: "3.7"

services:
  api:
    build: api
    command: runserver 0.0.0.0:80
    volumes:
      - ./api/api:/usr/src/app/api
      - ./api/project:/usr/src/app/project
    environment:
      AWS_S3_ENDPOINT_URL: http://127.0.0.1:9000
      AWS_S3_ENDPOINT_URL_PROXY: http://storage:9000
      SECRET_KEY: "django_secret"
    ports:
      - 8001:80

  web:
    build: web
    command: npm run dev -- -H 0.0.0.0 -p 80
    volumes:
      - ./web/assets:/usr/src/app/assets
      - ./web/components:/usr/src/app/components
      - ./web/layouts:/usr/src/app/layouts
      - ./web/middleware:/usr/src/app/middleware
      - ./web/pages:/usr/src/app/pages
      - ./web/plugins:/usr/src/app/plugins
      - ./web/static:/usr/src/app/static
      - ./web/store:/usr/src/app/store
      - ${PWD}/web/nuxt.config.js:/usr/src/app/nuxt.config.js
    ports:
      - 8000:80

  db:
    image: postgres:11.5-alpine

  storage:
    image: minio/minio
    command: server /data
    volumes:
      - /data
    environment:
      MINIO_ACCESS_KEY: access_key
      MINIO_SECRET_KEY: secret_key
    ports:
      - 9000:9000
