version: "3.7"

services:
  traefik:
    image: traefik:v2.0
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yml:/etc/traefik/traefik.yml
      - ./acme.json:/acme.json
    labels:
      - traefik.http.middlewares.https-redirect.redirectscheme.scheme=https
      - traefik.http.middlewares.auth.basicauth.users=${BASIC_AUTH}
      - traefik.http.routers.api-non-tls.rule=Host(`traefik.personamobile.ru`)
      - traefik.http.routers.api-non-tls.entrypoints=web
      - traefik.http.routers.api-non-tls.middlewares=https-redirect
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.rule=Host(`traefik.personamobile.ru`)
      - traefik.http.routers.api.service=api@internal
      - traefik.http.routers.api.middlewares=auth
      - traefik.http.routers.api.entrypoints=web-secure
      - traefik.http.routers.api.tls.certresolver=sample
    environment:
      CF_API_EMAIL: ${CF_API_EMAIL}
      CF_API_KEY: ${CF_API_KEY}

  backend:
    image: pocketguy/personamobile-api:latest
    environment:
      AWS_S3_ENDPOINT_URL: http://storage:9000/
      AWS_S3_CUSTOM_DOMAIN: storage.personamobile.ru/django
      SECRET_KEY: ${API_SECRET_KEY}
      DB_PASSWORD: ${DB_PASSWORD}
      AWS_ACCESS_KEY: ${STORAGE_ACCESS_KEY}
      AWS_SECRET_KEY: ${STORAGE_SECRET_KEY}
      DEBUG: "False"
      SITE_URL: https://www.personamobile.ru
    labels:
      - traefik.http.routers.backend.rule=Host(`api.personamobile.ru`)
      - traefik.http.routers.backend.middlewares=https-redirect
      - traefik.http.routers.backend.entrypoints=web
      - traefik.http.routers.backend-tls.rule=Host(`api.personamobile.ru`)
      - traefik.http.routers.backend-tls.tls=true
      - traefik.http.routers.backend-tls.entrypoints=web-secure
      - traefik.http.routers.backend-tls.tls.certresolver=sample

  web:
    image: pocketguy/personamobile-web:latest
    labels:
      - traefik.http.routers.web.rule=Host(`www.personamobile.ru`)
      - traefik.http.routers.web.middlewares=https-redirect
      - traefik.http.routers.web.entrypoints=web
      - traefik.http.routers.web-tls.rule=Host(`www.personamobile.ru`)
      - traefik.http.routers.web-tls.tls=true
      - traefik.http.routers.web-tls.entrypoints=web-secure
      - traefik.http.routers.web-tls.tls.certresolver=sample
    environment:
      AXIOS_BASE_URL: http://backend/
      AXIOS_BROWSER_BASE_URL: https://api.personamobile.ru/

  db:
    image: postgres:11.5-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db:/var/lib/postgresql/data
    labels:
      - traefik.enable=false
  storage:
    image: minio/minio
    command: server /data
    volumes:
      - storage:/data
    environment:
      MINIO_ACCESS_KEY: ${STORAGE_ACCESS_KEY}
      MINIO_SECRET_KEY: ${STORAGE_SECRET_KEY}
    labels:
      - traefik.http.routers.storage.rule=Host(`storage.personamobile.ru`)
      - traefik.http.routers.storage.middlewares=https-redirect
      - traefik.http.routers.storage.entrypoints=web
      - traefik.http.routers.storage-tls.rule=Host(`storage.personamobile.ru`)
      - traefik.http.routers.storage-tls.tls=true
      - traefik.http.routers.storage-tls.entrypoints=web-secure
      - traefik.http.routers.storage-tls.tls.certresolver=sample

volumes:
  db:
  storage:
