entryPoints:
  web:
    address: ":80"
  web-secure:
    address: ":443"

providers:
  docker: {}

api: {}

certificatesResolvers:
  sample:
    acme:
      email: pocketguy@protonmail.com
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0
