entryPoints:
  web:
    address: ":80"
  web-secure:
    address: ":443"
  postgres:
    address: ":5432"

providers:
  docker: {}

api:
  insecure: true

certificatesResolvers:
  sample:
    acme:
      email: pocketguy@protonmail.com
      storage: acme.json
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0
